export const elementos = {
    pantallaInicio: document.querySelector('#pantalla-inicio'),
    pantallaJuego: document.querySelector('#pantalla-juego'),
    listaRanking: document.querySelector('#lista-ranking'),
    inputNombre: document.querySelector('#input-nombre'),
    btnContinuar: document.querySelector('#btn-continuar'),
    btnVolverRanking: document.querySelector('#btn-volver-ranking'),
    ronda: document.querySelector('#ronda'),
    contenedorMano: document.querySelector('#mano'),
    listaPagos: document.querySelector('#tabla-pagos'),
    fichas: document.querySelector('#fichas'),
    inputApuesta: document.querySelector('#input-apuesta'),
    mensaje: document.querySelector('#mensaje'),
    btnApostar: document.querySelector('#btn-apostar'),
    btnCambiar: document.querySelector('#btn-cambiar'),
    btnPasar: document.querySelector('#btn-pasar'),
    btnNuevaPartida: document.querySelector('#btn-nueva-partida'),
};
