export const elementos = {
    pantallaInicio: document.querySelector('#pantalla-inicio'),
    pantallaJuego: document.querySelector('#pantalla-juego'),
    listaRanking: document.querySelector('#lista-ranking'),
    inputNombre: document.querySelector('#input-nombre'),
    btnContinuar: document.querySelector('#btn-continuar'),
    btnVolverRanking: document.querySelector('#btn-volver-ranking'),
    indicadorMano: document.querySelector('#indicador-mano'),
    contenedorMano: document.querySelector('#mano'),
    contenedorManoMaquina: document.querySelector('#mano-maquina'),
    listaRankingManos: document.querySelector('#ranking-manos'),
    fichasJugador: document.querySelector('#fichas-jugador'),
    fichasMaquina: document.querySelector('#fichas-maquina'),
    bote: document.querySelector('#bote'),
    mensaje: document.querySelector('#mensaje'),
    accionesRepartir: document.querySelector('#acciones-repartir'),
    accionesDescarte: document.querySelector('#acciones-descarte'),
    inputApuesta: document.querySelector('#input-apuesta'),
    btnRepartir: document.querySelector('#btn-repartir'),
    btnCambiar: document.querySelector('#btn-cambiar'),
    btnNuevaPartida: document.querySelector('#btn-nueva-partida'),
};
